"""
This stub file provides typing for Melissa's Address Object Python wrapper.

Note that original wrapper redefined many enum classes in module scope, which
only keeps the last definition. We may want to fix that is it causes issues.
"""

from __future__ import annotations

import enum


# noinspection PyPep8Naming, SpellCheckingInspection
class mdAddr:
    """
    Melissa has documentation spread uniquely across multiple subdomains:
    * https://docs.melissa.com/on-premise-api/address-object/address-object-reference-guide.html
    # https://wiki.melissadata.com/index.php?title=Address_Object
    * https://www.melissa.com/reference-guides/address-object
    """

    def Initialize(self, p1, p2, p3) -> ProgramStatus: ...
    def InitializeDataFiles(self) -> ProgramStatus: ...
    def GetInitializeErrorString(self) -> str: ...
    def SetLicenseString(self, p1: str) -> bool: ...
    def GetBuildNumber(self) -> str: ...
    def GetDatabaseDate(self) -> str: ...
    def GetExpirationDate(self) -> str: ...
    def GetLicenseExpirationDate(self) -> str: ...
    def GetCanadianDatabaseDate(self) -> str: ...
    def GetCanadianExpirationDate(self) -> str: ...

    def SetPathToUSFiles(self, /, p1: str) -> None: ...
    def SetPathToCanadaFiles(self, p1: str) -> None: ...
    def SetPathToDPVDataFiles(self, p1: str) -> None: ...
    def SetPathToLACSLinkDataFiles(self, p1: str) -> None: ...
    def SetPathToSuiteLinkDataFiles(self, p1: str) -> None: ...
    def SetPathToSuiteFinderDataFiles(self, p1: str) -> None: ...
    def SetPathToRBDIFiles(self, p1: str) -> None: ...
    def GetRBDIDatabaseDate(self) -> str: ...
    def SetPathToAddrKeyDataFiles(self, p1: str) -> None: ...

    def ClearProperties(self) -> None: ...
    def ResetDPV(self) -> None: ...
    def SetCASSEnable(self, is_enabled: bool) -> None: ...
    def SetUseUSPSPreferredCityNames(self, p1: bool) -> None: ...
    def SetDiacritics(self, p1: DiacriticsMode) -> None: ...
    def GetStatusCode(self) -> str: ...
    def GetErrorCode(self) -> str: ...
    def GetErrorString(self) -> str: ...
    def GetResults(self) -> str: ...
    def GetResultCodeDescription(
        self, resultCode: str, opt: ResultCdDescOpt = ResultCdDescOpt.ResultCodeDescriptionLong
    ) -> str:
        # https://docs.melissa.com/on-premise-api/name-object/name-object-quickstart.html#get-the-melissa-result-codes
        ...

    def SetPS3553_B1_ProcessorName(self, p1: str) -> None: ...
    def SetPS3553_B4_ListName(self, p1: str) -> None: ...
    def SetPS3553_D3_Name(self, p1: str) -> None: ...
    def SetPS3553_D3_Company(self, p1: str) -> None: ...
    def SetPS3553_D3_Address(self, p1: str) -> None: ...
    def SetPS3553_D3_City(self, p1: str) -> None: ...
    def SetPS3553_D3_State(self, p1: str) -> None: ...
    def SetPS3553_D3_ZIP(self, p1: str) -> None: ...
    def GetFormPS3553(self) -> str: ...
    def SaveFormPS3553(self, p1: str) -> None: ...
    def ResetFormPS3553(self) -> None: ...
    def ResetFormPS3553Counter(self) -> None: ...

    def SetStandardizationType(self, mode: StandardizeMode) -> None: ...
    def SetSuiteParseMode(self, mode: SuiteParseMode) -> None: ...
    def SetAliasMode(self, mode: AliasPreserveMode) -> None: ...

    def GetFormSOA(self) -> str: ...
    def SaveFormSOA(self, p1) -> None: ...
    def ResetFormSOA(self) -> None: ...
    def SetSOACustomerInfo(self, customerName: str, customerAddress: str) -> None: ...  # Canada only
    def SetSOACPCNumber(self, CPCNumber: str) -> None: ...  # Canada only
    def GetSOACustomerInfo(self) -> str: ...  # Canada only
    def GetSOACPCNumber(self) -> str: ...  # Canada only
    def GetSOATotalRecords(self) -> str: ...  # Canada only
    def GetSOAAAPercentage(self) -> str: ...  # Canada only
    def GetSOAAAExpiryDate(self) -> str: ...  # Canada only
    def GetSOASoftwareInfo(self) -> str: ...  # Canada only
    def GetSOAErrorString(self) -> str: ...  # Canada only

    def SetCompany(self, p1: str) -> None: ...
    def SetLastName(self, p1: str) -> None: ...
    def SetAddress(self, p1: str) -> None: ...
    def SetAddress2(self, p1: str) -> None: ...
    def SetLastLine(self, p1: str) -> None: ...
    def SetSuite(self, p1: str) -> None: ...
    def SetCity(self, p1: str) -> None: ...
    def SetState(self, p1: str) -> None: ...
    def SetZip(self, p1: str) -> None: ...
    def SetPlus4(self, p1: str) -> None: ...
    def SetUrbanization(self, p1: str) -> None: ...
    def SetCountryCode(self, p1: str) -> None: ...

    def SetParsedAddressRange(self, p1: str) -> None: ...
    def SetParsedPreDirection(self, p1: str) -> None: ...
    def SetParsedStreetName(self, p1: str) -> None: ...
    def SetParsedSuffix(self, p1: str) -> None: ...
    def SetParsedPostDirection(self, p1: str) -> None: ...
    def SetParsedSuiteName(self, p1: str) -> None: ...
    def SetParsedSuiteRange(self, p1: str) -> None: ...
    def SetParsedRouteService(self, p1: str) -> None: ...
    def SetParsedLockBox(self, p1: str) -> None: ...
    def SetParsedDeliveryInstallation(self, p1: str) -> None: ...
    def VerifyAddress(self) -> bool: ...

    def GetCompany(self) -> str: ...
    def GetLastName(self) -> str: ...
    def GetAddress(self) -> str: ...
    def GetAddress2(self) -> str: ...
    def GetSuite(self) -> str: ...
    def GetCity(self) -> str: ...
    def GetCityAbbreviation(self) -> str: ...
    def GetState(self) -> str: ...
    def GetZip(self) -> str: ...
    def GetPlus4(self) -> str: ...
    def GetCarrierRoute(self) -> str: ...
    def GetDeliveryPointCode(self) -> str: ...
    def GetDeliveryPointCheckDigit(self) -> str: ...
    def GetCountyFips(self) -> str: ...
    def GetCountyName(self) -> str: ...
    def GetAddressTypeCode(self) -> str: ...
    def GetAddressTypeString(self) -> str: ...
    def GetUrbanization(self) -> str: ...
    def GetCongressionalDistrict(self) -> str: ...
    def GetLACS(self) -> str: ...
    def GetLACSLinkIndicator(self) -> str: ...
    def GetPrivateMailbox(self) -> str: ...
    def GetTimeZoneCode(self) -> str: ...
    def GetTimeZone(self) -> str: ...
    def GetMsa(self) -> str: ...
    def GetPmsa(self) -> str: ...
    def GetDefaultFlagIndicator(self) -> str: ...
    def GetSuiteStatus(self) -> str: ...
    def GetEWSFlag(self) -> str: ...
    def GetCMRA(self) -> str: ...
    def GetDsfVacant(self) -> str: ...
    def GetCountryCode(self) -> str: ...
    def GetZipType(self) -> str: ...
    def GetFalseTable(self) -> str: ...
    def GetDPVFootnotes(self) -> str: ...
    def GetLACSLinkReturnCode(self) -> str: ...
    def GetSuiteLinkReturnCode(self) -> str: ...
    def GetRBDI(self) -> str: ...
    def GetELotNumber(self) -> str: ...
    def GetELotOrder(self) -> str: ...
    def GetAddressKey(self) -> str: ...
    def GetMelissaAddressKey(self) -> str: ...
    def GetMelissaAddressKeyBase(self) -> str: ...

    def GetOutputParameter(self, p1: str) -> str: ...
    def SetInputParameter(self, p1: str, p2: str) -> None: ...

    def FindSuggestion(self) -> bool: ...
    def FindSuggestionNext(self) -> bool: ...

    def GetDsfNoStats(self) -> str: ...
    def GetDsfDNA(self) -> str: ...

    def GetPS3553_B6_TotalRecords(self) -> str: ...
    def GetPS3553_C1a_ZIP4Coded(self) -> str: ...
    def GetPS3553_C1c_DPBCAssigned(self) -> str: ...
    def GetPS3553_C1d_FiveDigitCoded(self) -> str: ...
    def GetPS3553_C1e_CRRTCoded(self) -> str: ...
    def GetPS3553_C1f_eLOTAssigned(self) -> str: ...
    def GetPS3553_E_HighRiseDefault(self) -> str: ...
    def GetPS3553_E_HighRiseExact(self) -> str: ...
    def GetPS3553_E_RuralRouteDefault(self) -> str: ...
    def GetPS3553_E_RuralRouteExact(self) -> str: ...

    def GetZip4HRDefault(self) -> str: ...
    def GetZip4HRExact(self) -> str: ...
    def GetZip4RRDefault(self) -> str: ...
    def GetZip4RRExact(self) -> str: ...

    def GetPS3553_E_LACSCount(self) -> str: ...
    def GetPS3553_E_EWSCount(self) -> str: ...
    def GetPS3553_E_DPVCount(self) -> str: ...
    def GetPS3553_X_POBoxCount(self) -> str: ...
    def GetPS3553_X_HCExactCount(self) -> str: ...
    def GetPS3553_X_FirmCount(self) -> str: ...
    def GetPS3553_X_GenDeliveryCount(self) -> str: ...
    def GetPS3553_X_MilitaryZipCount(self) -> str: ...
    def GetPS3553_X_NonDeliveryCount(self) -> str: ...
    def GetPS3553_X_StreetCount(self) -> str: ...
    def GetPS3553_X_HCDefaultCount(self) -> str: ...
    def GetPS3553_X_OtherCount(self) -> str: ...
    def GetPS3553_X_LacsLinkCodeACount(self) -> str: ...
    def GetPS3553_X_LacsLinkCode00Count(self) -> str: ...
    def GetPS3553_X_LacsLinkCode14Count(self) -> str: ...
    def GetPS3553_X_LacsLinkCode92Count(self) -> str: ...
    def GetPS3553_X_LacsLinkCode09Count(self) -> str: ...
    def GetPS3553_X_SuiteLinkCodeACount(self) -> str: ...
    def GetPS3553_X_SuiteLinkCode00Count(self) -> str: ...

    def GetParsedAddressRange(self) -> str: ...
    def GetParsedPreDirection(self) -> str: ...
    def GetParsedStreetName(self) -> str: ...
    def GetParsedSuffix(self) -> str: ...
    def GetParsedPostDirection(self) -> str: ...
    def GetParsedSuiteName(self) -> str: ...
    def GetParsedSuiteRange(self) -> str: ...
    def GetParsedPrivateMailboxName(self) -> str: ...
    def GetParsedPrivateMailboxNumber(self) -> str: ...
    def GetParsedGarbage(self) -> str: ...
    def GetParsedRouteService(self) -> str: ...
    def GetParsedLockBox(self) -> str: ...
    def GetParsedDeliveryInstallation(self) -> str: ...

    def SetReserved(self, p1: str, p2: str) -> None: ...
    def GetReserved(self, p1: str) -> str: ...


# noinspection PyPep8Naming
class mdParse:
    """
    Melissa has documentation on a couple of subdomains:
    * https://docs.melissa.com/on-premise-api/address-object/address-object-reference-guide.html#parse-interface
    * https://www.melissa.com/reference-guides/address-object#ParseInterface
    """

    def Initialize(self, p1: str) -> ProgramStatus: ...
    def GetBuildNumber(self) -> str: ...

    def Parse(self, p1: str) -> bool: ...
    def ParseCanadian(self, p1: str) -> None: ...
    def ParseNext(self) -> bool: ...
    def LastLineParse(self, p1: str) -> None: ...

    def GetZip(self) -> str: ...
    def GetPlus4(self) -> str: ...
    def GetCity(self) -> str: ...
    def GetState(self) -> str: ...
    def GetStreetName(self) -> str: ...
    def GetRange(self) -> str: ...
    def GetPreDirection(self) -> str: ...
    def GetPostDirection(self) -> str: ...
    def GetSuffix(self) -> str: ...
    def GetSuiteName(self) -> str: ...
    def GetSuiteNumber(self) -> str: ...
    def GetPrivateMailboxNumber(self) -> str: ...
    def GetPrivateMailboxName(self) -> str: ...
    def GetGarbage(self) -> str: ...
    def GetRouteService(self) -> str: ...
    def GetLockBox(self) -> str: ...
    def GetDeliveryInstallation(self) -> str: ...

    def ParseRule(self) -> int: ...


# noinspection PyPep8Naming
class mdStreet:
    """
    Melissa has documentation on a couple of subdomains:
    * https://docs.melissa.com/on-premise-api/address-object/address-object-reference-guide.html#streetdata-interface
    * https://www.melissa.com/reference-guides/address-object#StreetDataInterface
    """

    def Initialize(self, p1: str, p2: str, p3: str) -> ProgramStatus: ...
    def GetInitializeErrorString(self) -> str: ...
    def GetDatabaseDate(self) -> str: ...
    def GetBuildNumber(self) -> str: ...
    def SetLicenseString(self, p1: str) -> bool: ...
    def GetLicenseExpirationDate(self) -> str: ...

    def FindStreet(self, p1: str, p2: str, p3: str) -> bool: ...
    def FindStreetNext(self) -> bool: ...

    def IsAddressInRange(self, p1: str, p2: str, p3: str) -> bool: ...
    def IsAddressInRange2(self, p1: str, p2: str, p3: str, p4: str) -> bool: ...

    def GetAutoCompletion(self, p1: str, p2: str, p3: AutoCompletionMode, p4: bool) -> str: ...
    def ResetAutoCompletion(self) -> None: ...

    def GetBaseAlternateIndicator(self) -> str: ...
    def GetLACSIndicator(self) -> str: ...
    def GetUrbanizationCode(self) -> str: ...
    def GetUrbanizationName(self) -> str: ...
    def GetLastLineNumber(self) -> str: ...
    def GetAddressType(self) -> str: ...
    def GetCongressionalDistrict(self) -> str: ...
    def GetCountyFips(self) -> str: ...
    def GetCompany(self) -> str: ...
    def GetCarrierRoute(self) -> str: ...
    def GetZip(self) -> str: ...
    def GetDeliveryInstallation(self) -> str: ...
    def GetPlus4High(self) -> str: ...
    def GetPlus4Low(self) -> str: ...
    def GetSuiteRangeOddEven(self) -> str: ...
    def GetSuiteRangeHigh(self) -> str: ...
    def GetSuiteRangeLow(self) -> str: ...
    def GetSuiteName(self) -> str: ...
    def GetPostDirection(self) -> str: ...
    def GetSuffix(self) -> str: ...
    def GetStreetName(self) -> str: ...
    def GetPreDirection(self) -> str: ...
    def GetPrimaryRangeOddEven(self) -> str: ...
    def GetPrimaryRangeHigh(self) -> str: ...
    def GetPrimaryRangeLow(self) -> str: ...


# mdZip Enumerations
class ProgramStatus(enum.IntEnum):
    ErrorNone = 0
    ErrorOther = 1
    ErrorOutOfMemory = 2
    ErrorRequiredFileNotFound = 3
    ErrorFoundOldFile = 4
    ErrorDatabaseExpired = 5
    ErrorLicenseExpired = 6


class AccessType(enum.IntEnum):
    Local = 0
    Remote = 1


class DiacriticsMode(enum.IntEnum):
    Auto = 0
    On = 1
    Off = 2


class StandardizeMode(enum.IntEnum):
    ShortFormat = 0
    LongFormat = 1
    AutoFormat = 2


class SuiteParseMode(enum.IntEnum):
    ParseSuite = 0
    CombineSuite = 1


class AliasPreserveMode(enum.IntEnum):
    ConvertAlias = 0
    PreserveAlias = 1


class AutoCompletionMode(enum.IntEnum):
    AutoCompleteSingleSuite = 0
    AutoCompleteRangedSuite = 1
    AutoCompletePlaceHolderSuite = 2
    AutoCompleteNoSuite = 3


class ResultCdDescOpt(enum.IntEnum):
    ResultCodeDescriptionLong = 0
    ResultCodeDescriptionShort = 1


class MailboxLookupMode(enum.IntEnum):
    MailboxNone = 0
    MailboxExpress = 1
    MailboxPremium = 2


# noinspection PyPep8Naming, SpellCheckingInspection
class mdZip(object):
    """
    Melissa has documentation on a couple of subdomains:
    * https://docs.melissa.com/on-premise-api/address-object/address-object-reference-guide.html#zipdata-interface
    * https://www.melissa.com/reference-guides/address-object#ZipDataInterface
    """

    def Initialize(self, p1: str, p2: str, p3: str) -> ProgramStatus: ...
    def GetInitializeErrorString(self) -> str: ...
    def GetDatabaseDate(self) -> str: ...
    def GetBuildNumber(self) -> str: ...
    def SetLicenseString(self, p1: str) -> bool: ...
    def GetLicenseExpirationDate(self) -> str: ...

    def FindZip(self, p1: str, p2: str) -> bool: ...
    def FindZipNext(self) -> bool: ...
    def FindZipInCity(self, p1: str, p2: str) -> str: ...
    def FindZipInCityNext(self) -> str: ...
    def FindCityInState(self, p1: str, p2: str) -> str: ...
    def FindCityInStateNext(self) -> str: ...

    def ComputeDistance(self, p1: int | float, p2: int | float, p3: int | float, p4: int | float) -> float: ...
    def ComputeBearing(self, p1: int | float, p2: int | float, p3: int | float, p4: int | float) -> float: ...

    def GetCountyNameFromFips(self, p1: str) -> str: ...
    def GetSCFArea(self, p1: str, p2: int, p3: int, p4: int, p5: int) -> str: ...

    def GetZip(self) -> str: ...
    def GetCity(self) -> str: ...
    def GetCityAbbreviation(self) -> str: ...
    def GetState(self) -> str: ...
    def GetZipType(self) -> str: ...
    def GetCountyName(self) -> str: ...
    def GetCountyFips(self) -> str: ...
    def GetAreaCode(self) -> str: ...
    def GetLongitude(self) -> str: ...
    def GetLatitude(self) -> str: ...
    def GetTimeZone(self) -> str: ...
    def GetTimeZoneCode(self) -> str: ...
    def GetMsa(self) -> str: ...
    def GetPmsa(self) -> str: ...
    def GetFacilityCode(self) -> str: ...
    def GetLastLineIndicator(self) -> str: ...
    def GetLastLineNumber(self) -> str: ...
    def GetPreferredLastLineNumber(self) -> str: ...
    def GetAutomation(self) -> str: ...
    def GetFinanceNumber(self) -> str: ...
